### ISSUE TITLE
Timer on homepage

### ISSUE THREAD

**Issue by sergiopera** [momocow/OGame-Redesign-v.6-Auction-Timer#1]
Hello would be great if you add a timer for remaining auction in homepage and for next auction also in homepage of ogame :D:D

i am using it and it's great.. Thanks for Sharing!

**Comment by momocow** [comment]
Hi, thanks for your response.

It's actually a bug since the original design has already had a timer displayed on the bar of each page except the auction page. It is because Ogame changed the protocol to HTTPS years ago and this script needs the URL to perform page detection. (this also reveals that this script is old and may be out-of-date.) It is fixed in 05ce6de so you can reinstall the script to have it correct.

Since the time for next auction is already an explicit (and predictable) time, it may be unnecessary to show the countdown timer for it. More discussion is needed with this feature.

If you meet with any other bugs, it is also welcome to file an issue here.

**Comment by sergiopera** [comment]
Thanks a lot, i love script 💃

**Comment by sergiopera** [comment]
I checked but still can't see the timer in overview.

I tried disabling all but still can't see the timer anywere.

https://gyazo.com/68ba0c0adb569909e22fdbbf77db8806

**Comment by momocow** [comment]
I think it is a compatibility problem with Antigame. (Both scripts compete the same display field.)
I'll check about it.

**Comment by sergiopera** [comment]
i tried without antigame with no luck

**Comment by momocow** [comment]
That was weird. 

Did you wait at the auction page for at least once OGame auction downcounter update? The script won't learn when the current auction ends until a OGame auction downcounter update.
That how it looks like after it has learned the ending time, screenshot from the overview page.  
 ![image](https://user-images.githubusercontent.com/17778751/36381979-5e3b1774-15c2-11e8-8b31-58098c0ef656.png)

If it still fails for you, check the console (by pressing F12) and see if any error is generated.

**Comment by sergiopera** [comment]
No nothing, let me show you: 
URL:
https://s151-en.ogame.gameforge.com/game/index.php?page=overview

![image](https://user-images.githubusercontent.com/35791291/36382365-65eb1074-1567-11e8-8a67-1ae571f2b024.png)

**Comment by sergiopera** [comment]
without any script:
![image](https://user-images.githubusercontent.com/35791291/36382440-a6c97202-1567-11e8-9118-f71816baa2bc.png)


i am using tampermonkey, is that ok?

**Comment by momocow** [comment]
Does the timer works well in your auction page?

I need more info to find out what was going on.
Press F12 at the **overview** page, check out "console" tab and take a screenshot in order to provide more error logs.

**Comment by sergiopera** [comment]
Yes in auction page works great... Gameforge disabled the console tab :(

**Comment by sergiopera** [comment]
Do you use with tampermonkey?

**Comment by momocow** [comment]
Yes. 

I'll test it on UK servers... waiting for the next auction to start.

**Comment by momocow** [comment]
Tests in UK servers passed.
![image](https://user-images.githubusercontent.com/17778751/36384261-aa6ed8cc-15c9-11e8-83b4-884ed5817873.png)

Try to have a clean update (remove the original script and re-install it again).
I found that I forgot to bump the version number, wondering if it may cause the update process to fail or not.

Make sure to install v2.1.1.

**Comment by momocow** [comment]
It is v2.1.1 now.

**Comment by sergiopera** [comment]
tried a clean install, and disabled everything in google chrome with tampermonkey. But no luck, is this for Gchrome?

![image](https://user-images.githubusercontent.com/35791291/36384861-8680eca2-156f-11e8-9f5f-00fdf4c7e554.png)

**Comment by momocow** [comment]
Yes, it's for chrome.

Wait at this page until the part as the following image counts to 10 min left, then go to overview and see if it works.
![image](https://user-images.githubusercontent.com/17778751/36384910-e6612d74-15cb-11e8-8b8f-2b7b0b032afa.png)

**Comment by sergiopera** [comment]
It's strange it's not working for me, but on auctioneer work perfect

**Comment by sergiopera** [comment]
do you use antigame?

**Comment by sergiopera** [comment]
yes working now 🗡

**Comment by sergiopera** [comment]
One suggestion, why not show time remaining for next auction?

**Comment by momocow** [comment]
Time for next auction is explicit and predictable. (Always at XX o'clock)

For example, 
It's 22:40 now.
Do you really need to know how much time left is 23:00?
Or should the script count for you that there is still 20 minutes to have a new auction?

**Comment by sergiopera** [comment]
You are right 👯

**Comment by momocow** [comment]
Thanks anyway.
It's always nice to have suggestion from others.

**Comment by sergiopera** [comment]
Thank you, for the script :D

**Comment by sergiopera** [comment]
I am testing it now, can you check with Antigame, because with antigame does not work.. Should show for example 40 min timer when enter to auction but not.
If you can add this compatibility will be great!

![image](https://user-images.githubusercontent.com/35791291/36400502-feee7e94-15af-11e8-8bb3-687affd42ed4.png)

**Comment by momocow** [comment]
I'll take a look by this weekend.

**Comment by sergiopera** [comment]
Well i saw some things, I saw that when you refresh timer goes out. There is one thing that i saw that is pretty predictable.

It finish exact time when timer changes
aprox 5min or aprox 10min is the real time remaining

So if server time is 00.50 and changes to 10 min remaining the script should LOCK timer to server time, in this case 01.00 to mark as that will end.

But when refresh is like the script bugs itself and reset his own timer.

Second i still don't see the timer remaining in my homepage

**Comment by momocow** [comment]
> So if server time is 00.50 and changes to 10 min remaining the script should LOCK timer to server time, in this case 01.00 to mark as that will end.

That is exactly the way that the script works and the only logic to **predict the real remaining time**.

The timer provided by the script should be self-correctable. That means when you see the remaining time provided by OGame updates, for example from "aprox 10min" to "aprox 5min", the script will correct its timer to match the update. (Let me name it as **"aprox-N-min" update**)

That also means if you see "aprox 5min" in your first visit to a certain auction, you will never get a real remaining time since there is no furthermore "aprox-N-min" update but a message shows that the auction just ended up.

> Second i still don't see the timer remaining in my homepage

As mentioned above, in order to see a timer in the homepage, you should **always** visit the auction page first and wait for **at least one "aprox-N-min" update** (Important!).

--------------------------

> But when refresh is like the script bugs itself and reset his own timer.

Weird. How many times (or the probability) that such kind of situation occurs?

In current version of script, the storage of the real remaining time predicted by the script depends on the [Local Storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) of the browser. Note that all modern browsers should have already implemented it.
In-memory data will not persist between page changes (or refreshes).

--------------------------

Besides, if there is no remaining time predicted by the script **stored in the Local Storage**, nothing will show up in the homepage. That may be a possible problem. More information of your platform is needed. 

By the way, you have mentioned that your console (opened by pressing F12) is disabled by Gameforge.
But this is impossible for a website to affect the browser decision and there is no way to do that.
Weird, also.

May I have your **Tampermonkey version**, **browser version** and **OS version**?

*If you are not using the latest version, it is suggested to have a update first.*

**Comment by momocow** [comment]
Add trackers.
- #3 *Provide a dependency detection mechanism*
- #4 *Implement a stateful timer*

**Comment by sergiopera** [comment]
Wait i am updating All

**Comment by sergiopera** [comment]
I have to wait 12 hours, so i will check.. Tempermonkey v45, Windows 10, chrome last version

**Comment by momocow** [comment]
Alright lol
May it works for you...

**Comment by sergiopera** [comment]
Maybe i am installing wrong... you have 3 files, but i just copy the code in tampermonkey of 1.. is that correct? i don't know how to install via GitHub

**Comment by momocow** [comment]
v3.0.1 now provides more error handling, logger messages and a stateful timer.
You can check out `README` to get more information.

A clean install of the script is recommended.

**Comment by skylinzz** [comment]
Hello, are you still updating the script? im having problemas with the timer... perhaps you could help me?
